/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Multicall } from "./Multicall";
export type { PinkPresale } from "./PinkPresale";
export * as factories from "./factories";
export { Multicall__factory } from "./factories/Multicall__factory";
export { PinkPresale__factory } from "./factories/PinkPresale__factory";
