/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { PinkPresale, PinkPresaleInterface } from "../PinkPresale";

const _abi = [
  {
    inputs: [],
    name: "contribute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class PinkPresale__factory {
  static readonly abi = _abi;
  static createInterface(): PinkPresaleInterface {
    return new utils.Interface(_abi) as PinkPresaleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PinkPresale {
    return new Contract(address, _abi, signerOrProvider) as PinkPresale;
  }
}
